import React from 'react'
import Head from 'next/head'
import styled from '@emotion/styled'
import { css, cx } from '@emotion/css'

const Button = styled.button`
  padding: 32px;
  background-color: hotpink;
  font-size: 24px;
  border-radius: 4px;
  color: black;
  font-weight: bold;
  cursor: pointer;
  transition: 1s ease-in;
  &:hover {
    color: white;
  }
`

export default function Home() {
  const color = 'white'
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Ultimate Project</main>
      <Button>This my button component.</Button>
      <div
        className={css`
          padding: 32px;
          background-color: hotpink;
          font-size: 24px;
          border-radius: 4px;
          &:hover {
            color: ${color};
          }
        `}
      >
        Hover to change color.
      </div>
    </div>
  )
}
