import Head from 'next/head'
import React from 'react'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import { InputEmail, InputPassword, Button, H2, Space } from '../components'
import FormControl from '../containers/FormControl/FormControl'

const login = () => {
  const handleSubmit = (e) => {
    e.preventDefault()
    console.log('handleSubmit')
  }

  return (
    <div className="container">
      <Head>
        <title>Login</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <Space />
        <H2>Welcome to Remote</H2>
        <form style={{ width: '30%' }} onSubmit={handleSubmit}>
          <FormControl>
            <InputEmail placeholder="Email" />
          </FormControl>
          <FormControl>
            <InputPassword placeholder="Password" />
          </FormControl>
          <FormControl>
            <Button type="submit">Submit</Button>
          </FormControl>
        </form>
      </LayoutAuth>
    </div>
  )
}

export default login
