import Head from 'next/head'
import React, { useState } from 'react'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import { InputPassword, Button, H2, Space } from '../components'
import FormControl from '../containers/FormControl/FormControl'

const Reset = () => {
  const [formValue, setFormValue] = useState({})

  const handleSubmit = (e) => {
    e.preventDefault()
    console.log('handleSubmit', formValue)
  }

  const handleChange = (name, value) => {
    setFormValue({
      ...formValue,
      [name]: value,
    })
  }

  return (
    <div className="container">
      <Head>
        <title>Reset</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutAuth>
        <Space />
        <H2>Reset your Password</H2>
        <form style={{ width: '30%' }} onSubmit={handleSubmit}>
          <FormControl>
            <InputPassword
              onChange={(value) => handleChange('password', value)}
              placeholder="Password"
            />
          </FormControl>
          <FormControl>
            <InputPassword
              onChange={(value) => handleChange('password', value)}
              placeholder="Confirm Password"
            />
          </FormControl>
          <FormControl>
            <Button widthAll type="submit">
              Submit
            </Button>
          </FormControl>
        </form>
      </LayoutAuth>
    </div>
  )
}

export default Reset
